In [4]:
!nvidia-smi


Sun May 25 09:09:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
import torch
print(torch.__version__)


2.6.0+cu124


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
MATRIX = torch.tensor([[7,8],
                       [6,6]])
MATRIX

tensor([[7, 8],
        [6, 6]])

In [9]:
TENSOR = torch.tensor([[[1,2,4],
                        [3,6,8],
                        [1,56,2]],
                       [[1,2,4],
                        [2,45,5],
                       [1,5,1]]])
TENSOR

tensor([[[ 1,  2,  4],
         [ 3,  6,  8],
         [ 1, 56,  2]],

        [[ 1,  2,  4],
         [ 2, 45,  5],
         [ 1,  5,  1]]])

In [10]:
TENSOR.shape

torch.Size([2, 3, 3])

RANDOM TENSORS

In [11]:
randomTensor = torch.rand(2,3,4)
randomTensor

tensor([[[0.3361, 0.5693, 0.2078, 0.9662],
         [0.5285, 0.6668, 0.6411, 0.2577],
         [0.7935, 0.0930, 0.2455, 0.1536]],

        [[0.8831, 0.7260, 0.6335, 0.2805],
         [0.4324, 0.1425, 0.7551, 0.8957],
         [0.7320, 0.1264, 0.6629, 0.3436]]])

In [12]:
randomimagesizeTensor = torch.rand(size=(3,224,224)) # color, height, width
randomimagesizeTensor


tensor([[[0.2113, 0.4062, 0.8569,  ..., 0.9865, 0.5303, 0.1993],
         [0.6498, 0.3562, 0.6537,  ..., 0.2862, 0.8760, 0.5665],
         [0.3075, 0.7634, 0.3482,  ..., 0.7314, 0.7986, 0.7493],
         ...,
         [0.5181, 0.8636, 0.0622,  ..., 0.3057, 0.3348, 0.0349],
         [0.3404, 0.3903, 0.8328,  ..., 0.9133, 0.1231, 0.7233],
         [0.0109, 0.5081, 0.3004,  ..., 0.7555, 0.5382, 0.3713]],

        [[0.1750, 0.6030, 0.8652,  ..., 0.0550, 0.7169, 0.8656],
         [0.8585, 0.4365, 0.3954,  ..., 0.0233, 0.8450, 0.2442],
         [0.8233, 0.1427, 0.5878,  ..., 0.7810, 0.4862, 0.2633],
         ...,
         [0.0224, 0.7636, 0.7823,  ..., 0.2432, 0.9722, 0.7658],
         [0.1449, 0.0716, 0.1510,  ..., 0.9799, 0.7313, 0.0644],
         [0.0929, 0.7994, 0.0377,  ..., 0.1635, 0.5185, 0.3716]],

        [[0.8091, 0.4048, 0.7906,  ..., 0.6327, 0.8138, 0.8366],
         [0.2272, 0.5880, 0.1459,  ..., 0.1732, 0.3508, 0.4702],
         [0.8133, 0.0487, 0.5360,  ..., 0.3786, 0.1336, 0.

In [13]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
zerotoHundred = torch.arange(start = 0, end = 1001, step = 100)
zerotoHundred

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [15]:
x = torch.arange(0,101, step = 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
x.argmin()

tensor(0)

In [17]:
x.argmax()

tensor(10)

In [18]:
# argmax/minn returns index of max/min

In [19]:
x = torch.rand(size=(224,224,3))
x_permuted = x.permute(2, 0, 1)
x.shape, x_permuted.shape



(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [20]:

#permute changes index of tensor dimensions

In [21]:
x = torch.arange(1, 10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
x[0,0]

tensor([1, 2, 3])

In [24]:
x[0,0,0]

tensor(1)

Numpy data to pytorch tensor and vice versa

In [25]:
import numpy as np
import torch

In [26]:
a = np.arange(1,8)
tensor = torch.from_numpy(a) # when converting, pytorch reflects np default datatype float64 and not float32
a, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [27]:
nparray = tensor.numpy()
nparray

array([1, 2, 3, 4, 5, 6, 7])

Reproducibility


In [ ]:
seed = 42
torch.manual_seed(seed)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(seed)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

In [3]:
 torch.cuda.is_available()

NameError: name 'torch' is not defined

In [ ]:
!nvidia-smi

In [ ]:
device = 'cuda' if torch.cuda.is_available() else cpu
tensor = torch.tensor([1,2,3])
tensoronGPU = tensor.to(device)
print(tensoronGPU)

In [ ]:
#Moving tensors back to CPU

In [ ]:
 tensoronCPU = tensoronGPU.cpu().numpy()
 tensoronCPU